train_file: ['iglue/datasets/xGQA/annotations/few_shot/{}/train_48.json',]
valid_file: ['iglue/datasets/xGQA/annotations/few_shot/{}/test.json']

answer_list: 'iglue/datasets/gqa/annotations/trainval_ans2label.json'
vqa_root: 'images/gqa/'


# zero-shot test set
test_file: {}


## Vision Encoder
vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False
#image_res: 384
#patch_size: 16

use_swin: True
image_res: 384
patch_size: 32


## Text Encoder (& Cross Encoder)
text_encoder: 'data/xlm-roberta-large'
text_num_hidden_layers: 12



## Training
num_dec_layers: 6
batch_size_train: 32
batch_size_test: 4
max_tokens: 40
k_test: 128



## Other Settings
optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 1e-5, epochs: 60, num_warmup_steps: 0.1}
start_eval: 9  # epoch index
eval_interval: 10
